server:
  port: 8083
    
eureka:
  instance:
    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8082/eureka
      
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customers/**
        
      - id: ACCOUNT-SERVICE
        uri: lb://ACCOUNT-SERVICE
        predicates:
        - Path=/accounts/**
        
  config:
    import: optional:configserver:http://localhost:8084
      

